PProject/Models/UserManagement/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AuthDB.Model.Interfaces;

namespace PProject.Models.UserManagement
{
    public class RoleViewModel : IRoleModel
    {
        public string RoleId { get; set; }
        public string UserId { get; set; }
    }
}

PProject/Models/UserManagement/UserEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DB.Common.Enums;

namespace PProject.Models.UserManagement
{
    public class UserEditViewModel
    {
        public UserViewModel User { get; set; }
        public List<AvailableRoles> Roles { get; set; }
    }
}

PProject/Models/UserManagement/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AuthDB.Model.Interfaces;

namespace PProject.Models.UserManagement
{
    public class UserViewModel : IUserModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTime? LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    }
}

PProject/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthDB.Model.Implementation;
using DB.Services.Interfaces;
using AuthDB.Services.Interfaces;
using DB.Common.Enums;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PProject.App_Start;
using PProject.Mapper;
using PProject.Models;
using PProject.Models.Faults;
using PProject.Models.UserManagement;

namespace PProject.Controllers
{
    [Authorize]
    public class UserManagementController : Controller
    {
        #region Members
        private readonly IUserService userService;

        #endregion MembersS

        #region Ctor
        public UserManagementController(IUserService userService)
        {
            this.userService = userService;
        }
        #endregion Ctor
        [AuthorizeRole(AvailableRoles.UserManagement, AvailableRoles.Administrator)]
        public ActionResult Index()
        {
            var viewModel = new ListViewModel<UserViewModel>() { Items = new List<UserViewModel>() };

            var result = userService.GetAllUsers();

            result.ForEach(u => viewModel.Items.Add(ViewModelMapper.Mapper.Map<UserViewModel>(u)));

            return View(viewModel);
        }
        /// <summary>
        /// Retrieves data for given user editing form.S
        /// </summary>
        /// <returns></returns>
        [AuthorizeRole(AvailableRoles.UserManagement, AvailableRoles.Administrator)]
        public ActionResult EditUser(string userId)
        {
            var queryResult = userService.GetUserById(userId);
            var userRoles = userService.GetUserRoles(queryResult.Id);

            var userViewModel = new List<AvailableRoles>();
            foreach (var role in userRoles)
            {
                AvailableRoles parsedRole;
                if (Enum.TryParse(role.RoleId, out parsedRole))
                {
                    userViewModel.Add(parsedRole);
                }
            }

            var viewModel = new UserEditViewModel();
            viewModel.User = ViewModelMapper.Mapper.Map<UserViewModel>(queryResult);
            viewModel.Roles = userViewModel;

            return View(viewModel);
        }
        [AuthorizeRole(AvailableRoles.UserManagement, AvailableRoles.Administrator)]
        public void ConfirmEditUser(string userId, string email, string phoneNumber, string[] roles)
        {
            var userModel = new UserModel()
            {
                Id = userId,
                Email = email,
                PhoneNumber = phoneNumber
            };

            var newRoles = new List<RoleModel>();
            if (roles != null)
            {
                foreach (var role in roles)
                {
                    newRoles.Add(new RoleModel()
                    {
                        UserId = userId,
                        RoleId = role
                    });
                }
            }
            
            userService.EditUserBasicData(userModel, newRoles);
        }
        /// <summary>
        /// Deletes user from the database.
        /// </summary>
        /// <param name="userId">RoleId of the user to delete.</param>
        /// <returns></returns>
        [AuthorizeRole(AvailableRoles.UserManagement, AvailableRoles.Administrator)]
        public void DeleteUser(string userId)
        {
            var issuingUserId = User.Identity.GetUserId();
            userService.DeleteUser(issuingUserId, userId);
        }
    }
}

PProject/Views/UserManagement/EditUser.cshtml
@using DB.Common.Enums
@model PProject.Models.UserManagement.UserEditViewModel
@{
    ViewBag.Title = "Edit User";
}
<input value="@Model.User.Id" id="userId" style="visibility: hidden">

<div id="editInputs" class="container" style="float: left; width: 100%">
    <div class="jumbotron">
        <h2>@ViewBag.Title</h2>
        <div id="forms" class="container-fluid">
            <div id="email" class="md-form">
                <input value="@Model.User.Email" type="text" id="emailInput" class="form-control">
                <label for="emailInput">E-mail</label>
            </div>
            <div id="phoneNumber" class="md-form">
                <input value="@Model.User.PhoneNumber" type="text" id="phoneNumberInput" class="form-control">
                <label for="phoneNumberInput">Phone Number</label>
            </div>
        </div>

        <div id="rolesBox" class="container-fluid">
            <div id="rolesContainer" class="custom-control custom-checkbox">
                <input id="role@(AvailableRoles.Administrator)" type="checkbox" data-role-name="@(AvailableRoles.Administrator)" 
                       class="custom-control-input" checked="@(Model.Roles.Exists(role => role.Equals(AvailableRoles.Administrator)))">
                <label class="custom-control-label" for="role@(AvailableRoles.Administrator)">@(AvailableRoles.Administrator)</label>
            </div>
            <div class="custom-control custom-checkbox">
                <input id="role@(AvailableRoles.Janitor)" type="checkbox" data-role-name="@(AvailableRoles.Janitor)" 
                       class="custom-control-input" checked="@(Model.Roles.Exists(role => role.Equals(AvailableRoles.Janitor)))">
                <label class="custom-control-label" for="role@(AvailableRoles.Janitor)">@(AvailableRoles.Janitor)</label>
            </div>
            <div class="custom-control custom-checkbox">
                <input id="role@(AvailableRoles.Overseer)" type="checkbox" data-role-name="@(AvailableRoles.Overseer)" 
                       class="custom-control-input" checked="@(Model.Roles.Exists(role => role.Equals(AvailableRoles.Overseer)))">
                <label class="custom-control-label" for="role@(AvailableRoles.Overseer)">@(AvailableRoles.Overseer)</label>
            </div>
            <div class="custom-control custom-checkbox">
                <input id="role@(AvailableRoles.Treasurer)" type="checkbox" data-role-name="@(AvailableRoles.Treasurer)" 
                       class="custom-control-input" checked="@(Model.Roles.Exists(role => role.Equals(AvailableRoles.Treasurer)))">
                <label class="custom-control-label" for="role@(AvailableRoles.Treasurer)">@(AvailableRoles.Treasurer)</label>
            </div>
            <div class="custom-control custom-checkbox">
                <input id="role@(AvailableRoles.UserManagement)" type="checkbox" data-role-name="@(AvailableRoles.UserManagement)" 
                       class="custom-control-input" checked="@(Model.Roles.Exists(role => role.Equals(AvailableRoles.UserManagement)))">
                <label class="custom-control-label" for="role@(AvailableRoles.UserManagement)">@(AvailableRoles.UserManagement)</label>
            </div>
        </div>
    </div>
</div>



<div id="controlButtons" class="container" style="float: right">
    <button onclick="onChangesConfirm()" type="button" class="btn btn-success">Confirm</button>
    <button onclick="onCancel()" type="button" class="btn btn-light">Cancel</button>
</div>

<div class="modal fade" id="wrongInputModal" tabindex="-1" role="dialog" aria-labelledby="wrongInputLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="wrongInputLabel">Incorrect input</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Email must be provided!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>

    function onChangesConfirm() {
        var userId = $('#userId')[0].value;
        var email = $('#emailInput')[0].value;
        var phoneNumber = $('#phoneNumberInput')[0].value;
        var newRoles = [];

        var allInputs = document.getElementsByTagName("input");//Get all available inputs

        for (var i = 0; i < allInputs.length; i++) {
            var control = allInputs[i];
            if (control.type === "checkbox") {//Only checkboxes interest us
                if (control.checked) {
                    newRoles.push(control.getAttribute("data-role-name"));//If any of them is checked - save its value.
                }
            }
        }

        if (!allNecessaryFieldsFilled(email)) {
            $('#wrongInputModal').modal('show'); //show popup - one of required data chunks is incomplete.
        } else {
            $.post("@Url.Action("ConfirmEditUser", "UserManagement")",
                {
                    userId: userId,
                    email: email,
                    phoneNumber: phoneNumber,
                    roles: newRoles
                }).then(function() {
                    location.href = '@Url.Action("Index", "UserManagement")';
                });
        }

    }
    function onCancel() {
        location.href = '@Url.Action("Index", "UserManagement")';
    }

    function allNecessaryFieldsFilled(email) {
        if (email === null) {
            return false; //show popup - one of required data chunks is incomplete.
        } else if (email === "") {
            return false; //show popup - one of required data chunks is incomplete.
        }

        return true;
    }
</script>

PProject/Views/UserManagement/Index.cshtml
@model PProject.Models.ListViewModel<PProject.Models.UserManagement.UserViewModel>
@{
    ViewBag.Title = "Users";
}


<div id="header" class="container" style="width:100%">
    <h2>@ViewBag.Title</h2>
</div>
<div id="tableContainer" class="container">
    <table id="usersTable" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th scope="col" class="col-sm-1"></th> <!--editing control-->
                <th scope="col" class="col-sm-1"></th> <!--removing control-->
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Phone Number</th>
                @*Iterate each element in model for given row in table.*@
            </tr>
        </thead>
        <tbody>
            @if (Model?.Items?.Count > 0)
            {
                foreach (var user in Model.Items)
                {
                    <tr>
                        <td><a href="@Url.Action("EditUser", "UserManagement")?userId=@user.Id"><i class="fas fa-book mr-2 grey-text hoverable" aria-hidden="true"></i></a></td>
                        <td><i class="fas fa-dumpster hoverable red-text" onclick="deleteRecord('@user.Id')"></i></td>
                        <td>@user.UserName</td>
                        <td>@user.Email</td>
                        <td>@user.PhoneNumber</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="11" style="text-align: center">No items to display.</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    ///Initializes the table.
    $(document).ready(function () {
        var table = $('#usersTable').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
    //Removes given residence from building.
    function deleteRecord(userId) {
        $.post("@Url.Action("DeleteUser", "UserManagement")",
            {
                userId: userId
            }).then(function() {
            window.location.href = window.location.href;
        });
    }

</script>

PProject/Views/UserManagement/RoleButtonView.cshtml
@using DB.Common.Enums
@model DB.Common.Enums.AvailableRoles


<button id="role@(Model.ToString())" type="button" class="btn" onclick="onButtonClick" data="@(Model.ToString())">
    @(Model.ToString())
</button>

<script>
    function onButtonClick(sender) {
        sender.color = "red";
    }
</script>