PProject/Models/Residents/ResidentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DB;
using DB.Model.Interfaces;

namespace PProject.Models.Residents
{
    public class ResidentViewModel : IResidentModel
    {
        public int id_najemcy { get; set; }
        public string nr_telefonu { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string PESEL { get; set; }
    }
}

PProject/Controllers/ResidentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Common.Enums;
using DB.Model.Implementation;
using DB.Services.Interfaces;
using PProject.App_Start;
using PProject.Mapper;
using PProject.Models;
using PProject.Models.Residents;

namespace PProject.Controllers
{
    [Authorize]
    public class ResidentsController : Controller
    {
        #region Members
        private readonly IResidentsService residentsService;

        #endregion Members

        #region Ctor
        public ResidentsController(IResidentsService residentsService)
        {
            this.residentsService = residentsService;
        }
        #endregion Ctor


        #region ActionMethods
        [AuthorizeRole(AvailableRoles.Overseer, AvailableRoles.Janitor, AvailableRoles.Administrator)]
        public ActionResult Index()
        {
            var viewModel = new ListViewModel<ResidentViewModel>() { Items = new List<ResidentViewModel>() };
            //Retrieve all residents.

            var result = residentsService.GetAllResidents();

            result.ForEach(u => viewModel.Items.Add(ViewModelMapper.Mapper.Map<ResidentViewModel>(u)));

            return View(viewModel);
        }



        /// <summary>
        /// Called to provide user edit form.
        /// </summary>
        /// <param name="residentId">ID of resident that will be edited.</param>
        /// <returns></returns>
        [AuthorizeRole(AvailableRoles.Overseer, AvailableRoles.Administrator)]
        public ActionResult EditResident(int? residentId)
        {
            ResidentViewModel viewModel = null;

            if (residentId != null)
            {
                var queryResult = residentsService.GetSingleResident((int)residentId);
                viewModel = ViewModelMapper.Mapper.Map<ResidentViewModel>(queryResult);
            }
            else
            {
                viewModel = new ResidentViewModel();
                viewModel.id_najemcy = -1;
            }

            return View(viewModel);
        }
        /// <summary>
        /// Accepts data from resident edit form
        /// </summary>
        /// <param name="residentId"></param>
        /// <param name="residentName"></param>
        /// <param name="residentSurname"></param>
        /// <param name="residentPhone"></param>
        /// <param name="residentPESEL"></param>
        [AuthorizeRole(AvailableRoles.Overseer, AvailableRoles.Administrator)]
        public void ConfirmResidentChange(int residentId, string residentName, string residentSurname, string residentPhone, string residentPESEL)
        {
            var newResident = new ResidentViewModel()
            {
                id_najemcy = residentId,
                imie = residentName,
                nazwisko = residentSurname,
                nr_telefonu = residentPhone,
                PESEL = residentPESEL
            };

            var preparedResident = ViewModelMapper.Mapper.Map<ResidentModel>(newResident);

            residentsService.AddOrEditResident(preparedResident);
        }
        #endregion ActionMethods
    }
}

PProject/Views/Residents/EditResident.cshtml
@model PProject.Models.Residents.ResidentViewModel
@{
    ViewBag.Title = "Edit Resident";
}
<input value="@Model.id_najemcy" id="residentId" style="visibility: hidden">

<div id="editInputs" class="container" style="float: left; width: 100%">
    <div class="jumbotron">
        <h2>@ViewBag.Title</h2>
        <div id="residentName" class="md-form">
            <input value="@Model.imie" type="text" id="residentNameInput" class="md-form">
            <label for="residentNameInput">Resident Name</label>
        </div>
        <div id="residentSurname" class="md-form">
            <input value="@Model.nazwisko" type="text" id="residentSurnameInput" class="md-form">
            <label for="residentSurnameInput">Resident Surname</label>
        </div>
        <div id="residentPhone" class="md-form">
            <input value="@Model.nr_telefonu" type="text" id="residentPhoneInput" class="md-form">
            <label for="residentPhoneInput">Mobile Number</label>
        </div>
        <div id="residentPESEL" class="md-form">
            <input value="@Model.PESEL" type="text" id="residentPESELInput" class="md-form">
            <label for="residentPESELInput">PESEL</label>
        </div>
    </div>
</div>

<div id="controlButtons" class="container" style="float: right">
    <button onclick="onChangesConfirm(@Model.id_najemcy)" type="button" class="btn btn-success">Confirm</button>
    <button onclick="onCancel(@Model.id_najemcy)" type="button" class="btn btn-light">Cancel</button>
</div>

<div class="modal fade" id="wrongInputModal" tabindex="-1" role="dialog" aria-labelledby="wrongInputLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="wrongInputLabel">Incorrect input</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                All positions must be filled!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    function onChangesConfirm() {
        var residentId = $('#residentId')[0].value;
        var residentName = $('#residentNameInput')[0].value;
        var residentSurname = $('#residentSurnameInput')[0].value;
        var residentPhone = $('#residentPhoneInput')[0].value;
        var residentPESEL = $('#residentPESELInput')[0].value;

        if (!allFieldsFilled(residentName, residentSurname, residentPhone, residentPESEL)) {
            $('#wrongInputModal').modal('show'); //show popup - one of required data chunks is incomplete.
        }else {
            $.post("@Url.Action("ConfirmResidentChange", "Residents")",
                {
                    residentId: residentId,
                    residentName: residentName,
                    residentSurname: residentSurname,
                    residentPhone: residentPhone,
                    residentPESEL: residentPESEL
                }).then(function() {
                location.href = '@Url.Action("Index", "Residents")';
            });
        }
    }

    function onCancel() {
        location.href = '@Url.Action("Index", "Residents")';
    }

    function allFieldsFilled(residentName, residentSurname, residentPhone, residentPESEL) {
        if (residentName === null || residentSurname === null
            || residentPhone === null || residentPESEL === null) {
            return false; //show popup - one of required data chunks is incomplete.
        } else if (residentName === "" || residentSurname === ""
            || residentPhone === "" || residentPESEL === "") {
            return false; //show popup - one of required data chunks is incomplete.
        }

        return true;
    }
</script>

PProject/Views/Residents/Index.cshtml
@model PProject.Models.ListViewModel<PProject.Models.Residents.ResidentViewModel>
@{
    ViewBag.Title = "Residents";
}

<div id="header" class="container" style="width:100%">
    <h2>Residents</h2>
    <a href="@Url.Action("EditResident", "Residents")"><i class="fas fa-plus fa-3x hoverable green-text"></i></a>
</div>


<div id="tableContainer" class="container">
    <table id="residentsTable" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th scope="col" class="col-sm-1"></th>
            <th scope="col" class="col-sm-1">Resident ID</th>
            <th scope="col">Phone</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">PESEL</th>
            @*Iterate each element in model for given row in table.*@
        </tr>
        </thead>
        <tbody>
        @if (Model?.Items?.Count > 0)
        {
            foreach (var resident in Model.Items)
             {
            <tr>
                <td><a href="@Url.Action("EditResident", "Residents")?residentId=@resident.id_najemcy"><i class="fas fa-book mr-2 grey-text hoverable"></i></a></td>
                <td>@resident.id_najemcy</td>
                <td>@resident.nr_telefonu</td>
                <td>@resident.imie</td>
                <td>@resident.nazwisko</td>
                <td>@resident.PESEL</td>
            </tr>
             }
        }
        else
        {
            <tr>
                <td colspan="6" style="text-align: center">No items to display.</td>
            </tr>
        }

        </tbody>
    </table>
</div>



<script>
    ///Initializes the table.
    $(document).ready(function () {
        var table = $('#residentsTable').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>