PProject/Controllers/LatePaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Common.Enums;
using DB.Model.Interfaces;
using DB.Services.Interfaces;
using PProject.App_Start;
using PProject.Mapper;
using PProject.Models;
using PProject.Models.Residents;

namespace PProject.Controllers
{
    [Authorize]
    public class LatePaymentsController : Controller
    {
        #region Members
        private readonly ILatePaymentService service;

        #endregion Members

        #region Ctor
        public LatePaymentsController(ILatePaymentService service)
        {
            this.service = service;
        }
        #endregion Ctor

        #region ActionMethods
        [AuthorizeRole(AvailableRoles.Overseer, AvailableRoles.Treasurer, AvailableRoles.Administrator)]
        public ActionResult Index()
        {
            var viewModel = new ListViewModel<ILatePaymentModel>() { Items = new List<ILatePaymentModel>() };
            //Retrieve all residents.

            var result = service.GetAllLatePayments();

            result.ToList().ForEach(u => viewModel.Items.Add(ViewModelMapper.Mapper.Map<ILatePaymentModel>(u)));

            return View(viewModel);
        }
        #endregion  
    }
}

PProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/MDB/js/bootstrap.min.js"></script>

    <link href="~/Scripts/MDB/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/MDB/css/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="padding: 0 0 0 0">
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#80E380">
        <div class="container">
            <div class="navbar-header" width="90%">
                <div class="d-flex" style="float: left">
                    <h2>Estate management</h2>
                </div>
            </div>
            <div class="d-flex" width="10%" style="float: right;">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="d-flex">
        <div class="navbar align-content-start" style="background-color: palegreen; height:100vh">
            <ul class="navbar-nav">
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Residents", "Index", "Residents")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Residences", "Index", "Residences")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Faults", "Index", "Faults")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Rentals", "Index", "Rental")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Companies", "Index", "Companies")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("User Management", "Index", "UserManagement")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Income", "Index", "Income")</h3></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link"><h3>@Html.ActionLink("Late Payments", "Index", "LatePayments")</h3></a>
                </li>
            </ul>
        </div>
        <div class="container body-content">
            @{
                var errors = (IEnumerable<string>) ViewBag.Errors ?? new List<string>();
                var messages = (IEnumerable<string>) ViewBag.Messages ?? new List<string>();
                foreach (var error in errors)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Error!</strong> @error
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                foreach (var message in messages)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @message
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
            }
            @RenderBody()
            <hr/>
            <footer>
                <p>&copy; @DateTime.Now.Year - Karol Kozuch & Friends</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>

    <script src="~/Scripts/MDB/js/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/MDB/js/addons/datatables.min.js"></script>
    <script src="~/Scripts/MDB/js/popper.min.js"></script>
    <script src="~/Scripts/MDB/js/bootstrap.min.js"></script>
    <script src="~/Scripts/MDB/js/mdb.min.js"></script>


</body>
</html>